name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
       # TODO: Update this to not remove once all dependent packages are approved in artifactory.
      - run: rm -f package-lock.json && npm install
      - name: Build sandbox container
        run: docker build -t ghcr.io/sgnl-actions/sandbox-runner:latest .
      - run: npm test
